# Generated by Django 2.1.7 on 2019-02-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usertest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tel', models.IntegerField(default=12345678911, max_length=11, null=True)),
                ('insert_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
