# Generated by Django 2.1.7 on 2019-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, 'youke'), (2, 'huiyuan'), (3, 'chaojiguanliyuan')], default=1)),
                ('status', models.BooleanField(default=True, help_text='开启或者禁用状态')),
                ('Text', models.TextField(null=True)),
                ('IP', models.GenericIPAddressField(default='127.0.0.1')),
                ('url', models.URLField(null=True)),
                ('file_path', models.FilePathField(null=True)),
                ('file', models.FileField(default='H:/1231', upload_to='H:/123')),
                ('img', models.ImageField(default='H:/1231', upload_to='H:/123')),
                ('insert_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
