# Generated by Django 2.1.7 on 2019-02-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='tel',
            field=models.IntegerField(default=12345678911, max_length=12, null=True),
        ),
    ]
