# Generated by Django 2.1.7 on 2019-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_path',
            field=models.FilePathField(null=True, path='H:/123'),
        ),
    ]
