# Generated by Django 2.1.7 on 2019-02-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190216_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='tel',
            field=models.IntegerField(default=12345678911, null=True),
        ),
    ]
