# Generated by Django 2.1.7 on 2019-02-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190218_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file_path',
        ),
    ]
