# Generated by Django 2.1.7 on 2019-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190218_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='/1231', upload_to='app/123'),
        ),
    ]
