# Generated by Django 2.1.7 on 2019-02-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payMx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jine', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
