# Generated by Django 2.1.7 on 2019-02-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_userinfo_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=64, null=True)),
                ('ctime', models.DateField(auto_now_add=True, null=True)),
                ('uptime', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='payMx',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=11111, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.FileField(default=1111, help_text='pwd', max_length=60, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.EmailField(error_messages={'invalid': 'shurumima'}, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, 'superuser'), (2, 'commonuser'), (3, 'com-commonuser')], default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Usergroup'),
        ),
    ]
