# Generated by Django 2.1.7 on 2019-02-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190215_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(max_length=62, null=True),
        ),
    ]
